export const PORTFOLIO_TEMPLATES = [
  {
    id: 'default',
    name: '\uae30\ubcf8',
    nameEn: 'Default',
    description: '\ubbf8\ub2c8\uba40 \ub9e4\uac70\uc9c4 \uc2a4\ud0c0\uc77c',
    defaults: { backgroundColor: '#FFFFFF', textColor: '#1A1A1A', accentColor: '#F4A259', columns: 3, photoGap: 8, pagePadding: 48, borderRadius: 12, fontFamily: 'pretendard' },
    headerVariant: 'left',
    gridVariant: 'masonry',
    filterVariant: 'floating',
    imageEffect: 'none',
    hoverEffect: 'overlay',
    gridBorder: false,
  },
  {
    id: 'bentobox',
    name: '\ubca4\ud1a0\ubc15\uc2a4',
    nameEn: 'Bento Box',
    description: '\ubd88\uaddc\uce59 \uadf8\ub9ac\ub4dc \ub808\uc774\uc544\uc6c3',
    defaults: { backgroundColor: '#F4F3EE', textColor: '#1A1A1A', accentColor: '#F4A259', columns: 4, photoGap: 16, pagePadding: 48, borderRadius: 24, fontFamily: 'poppins' },
    headerVariant: 'left-large',
    gridVariant: 'bento',
    filterVariant: 'underline',
    imageEffect: 'none',
    hoverEffect: 'overlay',
    gridBorder: false,
  },
  {
    id: 'casestudy',
    name: '\ucf00\uc774\uc2a4 \uc2a4\ud130\ub514',
    nameEn: 'Case Study',
    description: '\uc88c\uc6b0 \uad50\ucc28 \uce74\ub4dc \ub808\uc774\uc544\uc6c3',
    defaults: { backgroundColor: '#FFFFFF', textColor: '#1A1A1A', accentColor: '#F4A259', columns: 1, photoGap: 0, pagePadding: 48, borderRadius: 16, fontFamily: 'inter' },
    headerVariant: 'center',
    gridVariant: 'casestudy',
    filterVariant: 'underline-center',
    imageEffect: 'none',
    hoverEffect: 'zoom',
    gridBorder: false,
  },
  {
    id: 'cinematography',
    name: '\uc2dc\ub124\ub9c8\ud1a0\uadf8\ub798\ud53c',
    nameEn: 'Cinematography',
    description: '\ub2e4\ud06c \uc2f1\uae00 \ucee8\ub7fc',
    defaults: { backgroundColor: '#0D1B2A', textColor: '#E0E1DD', accentColor: '#778DA9', columns: 1, photoGap: 64, pagePadding: 80, borderRadius: 8, fontFamily: 'montserrat' },
    headerVariant: 'center',
    gridVariant: 'single',
    filterVariant: 'underline-center',
    imageEffect: 'none',
    hoverEffect: 'brightness',
    gridBorder: false,
  },
  {
    id: 'coloured',
    name: '\ucee8\ub7ec\ub4dc',
    nameEn: 'Coloured',
    description: '\uc0ac\uc774\ub4dc\ubc14 + \ub2e4\uc774\ub098\ubbf9 \ub118\ubc84',
    defaults: { backgroundColor: '#EBEAE5', textColor: '#1a1a1a', accentColor: '#E32015', columns: 2, photoGap: 24, pagePadding: 48, borderRadius: 16, fontFamily: 'inter' },
    headerVariant: 'sidebar',
    gridVariant: 'masonry',
    filterVariant: 'underline',
    imageEffect: 'none',
    hoverEffect: 'overlay',
    gridBorder: false,
  },
  {
    id: 'creative',
    name: '\ud06c\ub9ac\uc5d0\uc774\ud2f0\ube0c',
    nameEn: 'Creative',
    description: '\ucef4\ud329\ud2b8 \ubca4\ud1a0 \uadf8\ub9ac\ub4dc',
    defaults: { backgroundColor: '#F4F3EE', textColor: '#2C2C2C', accentColor: '#C19A6B', columns: 3, photoGap: 16, pagePadding: 40, borderRadius: 24, fontFamily: 'poppins' },
    headerVariant: 'left-compact',
    gridVariant: 'bento',
    filterVariant: 'pill',
    imageEffect: 'none',
    hoverEffect: 'zoom',
    gridBorder: false,
  },
  {
    id: 'editorial',
    name: '\uc5d0\ub514\ud1a0\ub9ac\uc5bc',
    nameEn: 'Editorial',
    description: '\ubcf4\ub354 \uadf8\ub9ac\ub4dc + \uadf8\ub808\uc774\uc2a4\ucf00\uc77c',
    defaults: { backgroundColor: '#FFFFFF', textColor: '#1A1A1A', accentColor: '#1A1A1A', columns: 2, photoGap: 0, pagePadding: 0, borderRadius: 0, fontFamily: 'inter' },
    headerVariant: 'center-large',
    gridVariant: 'editorial',
    filterVariant: 'underline-center',
    imageEffect: 'grayscale',
    hoverEffect: 'color-reveal',
    gridBorder: true,
  },
  {
    id: 'grey',
    name: '\uadf8\ub808\uc774',
    nameEn: 'Grey',
    description: '\uc2a4\uc704\uc2a4 \ub514\uc790\uc778 \ubca4\ud1a0',
    defaults: { backgroundColor: '#F5F5F5', textColor: '#1A1A1A', accentColor: '#F4A259', columns: 4, photoGap: 16, pagePadding: 48, borderRadius: 8, fontFamily: 'inter' },
    headerVariant: 'center',
    gridVariant: 'bento',
    filterVariant: 'underline-center',
    imageEffect: 'none',
    hoverEffect: 'gradient-overlay',
    gridBorder: false,
  },
]
